// <auto-generated />
using System;
using System.Collections.Generic;
using CVAnalyzer.Data;
using CVAnalyzer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CVAnalyzer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530191914_AddUserSkills")]
    partial class AddUserSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CVAnalyzer.Models.CandidateCV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<ATSParsedData>("ParsedData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CandidateCVs");
                });

            modelBuilder.Entity("CVAnalyzer.Models.JobRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("JobRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full-stack, frontend, backend",
                            IconClass = "ti-code",
                            IsActive = true,
                            RequiredSkills = "C#,ASP.NET,SQL,JavaScript,HTML,CSS,Git,API,React,Docker",
                            RoleName = "Software Developer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dijital, içerik, sosyal medya",
                            IconClass = "ti-speakerphone",
                            IsActive = true,
                            RequiredSkills = "SEO,Google Ads,Analytics,Content Marketing,Social Media,Email Marketing,Canva,CRM",
                            RoleName = "Marketing Specialist"
                        },
                        new
                        {
                            Id = 3,
                            Description = "B2B, müşteri yönetimi",
                            IconClass = "ti-chart-line",
                            IsActive = true,
                            RequiredSkills = "CRM,Negotiation,B2B,Pipeline,Salesforce,KPI,Forecasting,Cold Calling",
                            RoleName = "Sales Manager"
                        },
                        new
                        {
                            Id = 4,
                            Description = "SQL, Python, BI araçları",
                            IconClass = "ti-chart-bar",
                            IsActive = true,
                            RequiredSkills = "SQL,Python,Power BI,Tableau,Excel,Statistics,Machine Learning,ETL,R",
                            RoleName = "Data Analyst"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Figma, kullanıcı araştırması",
                            IconClass = "ti-palette",
                            IsActive = true,
                            RequiredSkills = "Figma,Adobe XD,User Research,Wireframing,Prototyping,CSS,Usability Testing,Design System",
                            RoleName = "UI/UX Designer"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Agile, Scrum, liderlik",
                            IconClass = "ti-layout-kanban",
                            IsActive = true,
                            RequiredSkills = "Agile,Scrum,Jira,Risk Management,Budgeting,Stakeholder Management,PMP,Leadership",
                            RoleName = "Project Manager"
                        });
                });

            modelBuilder.Entity("CVAnalyzer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CVAnalyzer.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Headline")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LinkedinUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<List<string>>("Skills")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("CVAnalyzer.Models.CandidateCV", b =>
                {
                    b.HasOne("CVAnalyzer.Models.User", "User")
                        .WithMany("CandidateCVs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVAnalyzer.Models.UserProfile", b =>
                {
                    b.HasOne("CVAnalyzer.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("CVAnalyzer.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CVAnalyzer.Models.User", b =>
                {
                    b.Navigation("CandidateCVs");

                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
